Translator_mapping = {
  "1go": "1GB",
  "2go": "2GB",
  "4go": "4GB",
  "8go": "8GB",
  "16go": "16GB",
  "32go": "32GB",
  "64go": "64GB",
  "128go": "128GB",
  "256go": "256GB",
  "512go": "512GB",
  "1": "1GB",
  "2": "2GB",
  "4": "4GB",
  "8": "8GB",
  "16": "16GB",
  "32": "32GB",
  "64": "64GB",
  "128": "128GB",
  "256": "256GB",
  "512": "512GB",
  "microsdhc8": "microsdhc 8GB",
  "microsdhc16": "microsdhc 16GB",
  "microsdhc32": "microsdhc 32GB",
  "microsdhc64": "microsdhc 64GB",
  "1400x": "210M B/s",
  "1000x": "150 MB/s",
  "667x": "100 MB/s",
  "300x": "45 MB/s",
  "200x": "30 MB/s",
  "memoria": "memory",
  "carte": "card",
  "de": "of",
  "pro":"professional",
  "tarjeta": "card",
  "pami": "memory",
  "speicherkarte": "memory card",
  "classe": "class",
  "ci": "here",
  "karta": "card",
  "mémoire": "memory",
  "clé": "memory",
  "es": "is",
  "adaptateur": "adapter",
  "minneskort": "memory card",
  "con": "with",
  "le": "the",
  "dans": "in",
  "rayon": "range",
  "adaptador": "adapter",
  "gen": "generation",
  "achat": "purchase",
  "zu": "until",
  "bis": "until",
  "hasta": "until",
  "di": "Of",
  "avec": "with",
  "scheda": "module",
  "jusqu": "until",
  "lecteur": "reader",
  "schwarz": "black",
  "adattatore": "adapter",
  "sek": "seconds",
  "minne": "memory",
  "laufwerk": "drive",
  "ab": "from",
  "clés": "memory",
  "sous": "below",
  "karty": "card",
  "speicherstick": "usb-memory",
  "saber": "know",
  "bei": "at",
  "da": "from",
  "till": "until",
  "unidad": "unit",
  "vitesse": "speed",
  "velocidad": "speed",
  "lectura": "reading",
  "geheugenkaart": "memory card",
  "kostenloser": "free",
  "przeno": "portable",
  "tarjetas": "cards",
  "tipo": "type",
  "fino": "until",
  "lecture": "reading",
  "foto": "photo",
  "versand": "shipping",
  "klasse": "class",
  "kamera": "Camera",
  "argent": "silver",
  "unità": "unit",
  "memorie": "memory",
  "jetzt": "now",
  "accesorios": "accessories",
  "allant": "going",
  "mit": "with",
  "blanco": "white",
  "flashgeheugenkaart": "flash memory card",
  "informática": "Information Technology",
  "sdsquar": "sd squar",
  "usm": "USB stick",
  "sdc10g2": "sd c10 g2",
  "et": "and",
  "adapt": "adaptor",
  "kupon": "coupon",
  "plata": "silver",
  "erný": "black",
  "rot": "red",
  "lesen": "read",
  "memóriakártya": "memory card",
  "abfoto": "foto",
  "bianco": "white",
  "rojo": "red",
  "inc": "incorporated",
  "offrez": "offer",
  "sans": "without",
  "azul": "blue",
  "bleu": "blue",
  "rosa": "pink",
  "incl": "included",
  "kaart": "card",
  "rouge": "red",
  "lector": "reader",
  "verde": "green",
  "bestellen": "order",
  "quot": "quote",
  "attaché": "attached",
  "llave": "memory",
  "attache": "attached",
  "kort": "card",
  "mem": "memory",
  "blau": "blue",
  "cle": "memory",
  "asdiscount": "discount",
  "argento": "silver",
  "la": "the",
  "met": "of",
  "portatile": "portable",
  "velocità": "speed",
  "chiavette": "memory",
  "warto": "worth",
  "rosso": "red",
  "czarny": "black",
  "wysokiej": "high",
  "memoire": "memory",
  "inkl": "included",
  "adaptor": "adapter",
  "lettura": "reading",
  "weiß": "white",
  "produty": "products",
  "zapisu": "write",
  "nouvelle": "new",
  "anthrazit": "anthracite",
  "extr": "extra",
  "zaprojektowana": "design",
  "vert": "green",
  "accessoires": "accessories",
  "verpackung": "packaging",
  "frustfreie": "frustration-free",
  "velocidades": "speed",
  "deluxe": "luxury",
  "les": "the",
  "zosta": "saved",
  "gelegt": "placed",
  "warenkorb": "shopping cart",
  "zwart": "black",
  "den": "the",
  "seconde": "second",
  "która": "which",
  "adap": "adapter",
  "und": "and",
  "ca": "about",
  "für": "for",
  "flashgeheugen": "flash memory",
  "pict": "picture",
  "plateado": "silver",
  "noire": "black",
  "typ": "type",
  "cam": "camera",
  "klí": "stick",
  "weiss": "white",
  "class4": "class 4",
  "jako": "as",
  "cartes": "cards",
  "connectique": "connectivity",
  "speicherkarten": "memory cards",
  "wit": "with",
  "medi": "medium",
  "vergini": "unused",
  "ntarjeta": "card",
  "actual": "current",
  "para": "until",
  "rose": "rose",
  "blu": "blue",
  "zilver": "silber",
  "grün": "green",
  "gris": "gray",
  "securedigital": "secure digital",
  "caméras": "cameras",
  "mercado": "market",
  "numero": "number",
  "aplikacja": "app",
  "imballaggio": "packaging",
  "connectés": "connected",
  "grucce": "hangers",
  "kovový": "metallic",
  "téléphone": "telephone",
  "kompatybilna": "compatible",
  "classe10": "class 10",
  "kappe": "cap",
  "transferu": "transfer",
  "grau": "gray",
  "minimaln": "minimal",
  "disque": "disk",
  "seule": "alone",
  "caméra": "camera",
  "massima": "maximum",
  "memória": "memory",
  "supporti": "supports",
  "bewegung": "movement",
  "niebieski": "blue",
  "tylko": "Just",
  "czytnikiem": "reader",
  "adatt": "adapter",
  "capacité": "capacity",
  "lebens": "life",
  "métal": "metal",
  "pojemno": "capacity",
  "incluso": "including",
  "moire": "glittering",
  "adapteur": "adapter",
  "inbegriffen": "included",
  "actionsc": "action camera",
  "trasparente": "transparent",
  "gwarantuj": "warranty",
  "eines": "one",
  "daten": "data",
  "preciosya": "Instant prices",
  "actioncam": "action camera",
  "appareils": "devices",
  "capacità": "capacity",
  "idéale": "ideal",
  "schede": "cards",
  "applicatives": "applications",
  "adattore": "adapter",
  "vidéo": "video",
  "serienaufnahmen": "video",
  "technische": "technical",
  "einfangen": "capture",
  "professionale": "professional",
  "vit": "white",
  "dur": "durable",
  "edición": "edition",
  "déballer": "unpack",
  "ohne": "without",
  "lettore": "reader",
  "svart": "black",
  "uniquement": "uniquely",
  "der": "the",
  "emballage": "packaging",
  "sin": "without",
  "geschwindigkeiten": "speeds",
  "inclus": "included",
  "temperatura": "temperature",
  "schreiben": "write",
  "incluye": "included",
  "industrielle": "industrial",
  "fekete": "black",
  "schnelle": "fast",
  "alta": "high",
  "dualdrive": "dual drive",
  "almacenamiento": "storage",
  "memoriausb3": "USB 3 memory",
  "limitada": "limited",
  "jumpdrivev10": "jumpdrive v10",
  "nur": "only",
  "externe": "external",
  "escritura": "writing",
  "profesionnelles": "professional",
  "coque": "body",
  "minnekort": "memory card",
  "czytnik": "reader",
  "anschluss": "connection",
  "bronze": "bronce",
  "ervený": "red",
  "azzurro": "sky blue",
  "etui": "case",
  "ní": "no",
  "ak": "and",
  "kártya": "card",
  "scrittura": "write",
  "grigio": "gray",
  "clef": "stick",
  "vidéosurveillance": "video surveillance",
  "externí": "extern",
  "gelb": "yellow",
  "vitesses": "speed",
  "lecteurs": "reader",
  "adaptateurs": "adapter",
  "elektrisches": "electric",
  "kamery": "camera",
  "naranjas": "orange",
  "adat": "adapter",
  "iscriviti": "sign up",
  "uya": "do you",
  "preis": "price",
  "posiada": "has",
  "idéal": "ideal",
  "modrý": "blue",
  "lesegeschwindigkeit": "reading speed",
  "gut": "good",
  "nuevo": "new",
  "mach": "do",
  "apertura": "aperture",
  "van": "by",
  "farbe": "color",
  "housse": "body",
  "un": "and",
  "clã": "clan",
  "verte": "green",
  "nera": "black",
  "computer_components": "computer components",
  "ezüst": "silver",
  "blå": "blue",
  "calidad": "quality",
  "differenzadivelocitàtrausb3": "speed difference usb 3",
  "archiviazioneesterna": "external storage",
  "archiviazione esterna": "external storage",
  "usbaelevateprestazioni": "usb high performance",
  "usb elevate prestazioni": "usb high performance",
  "0standard": "0 standard",
  "una": "a",
  "velocitàditrasferimentofilm": "transfer speed video",
  "velocità di trasferimento film": "transfer speed video",
  "unitàflashusb3": "usb 3 flashdrive",
  "externa": "external",
  "série": "series",
  "microcard": "microSD card",
  "voor": "for",
  "solido": "solid",
  "média": "media",
  "wykorzystuj": "use",
  "sconto": "discount",
  "uhsii": "uhs ii",
  "arancione": "orange",
  "kameras": "cameras",
  "portatil": "portable",
  "leer": "empty",
  "mobiltillbehör": "mobile accessories",
  "senza": "without",
  "sólido": "solid",
  "bleue": "blue",
  "sehr": "very",
  "électrique": "electronic",
  "rood": "red",
  "oraz": "and",
  "kapazität": "capacity",
  "electrónica": "electronic",
  "connecteur": "adapter",
  "class1": "class 1",
  "kaartlezer": "card reader",
  "avecadaptateur": "with adapter",
  "avec adaptateur": "with adapter",
  "viola": "violet",
  "memoriausb": "memory a usb",
  "réf": "reference",
  "azione": "action",
  "kortläsare": "card reader",
  "csatlakoz": "join in",
  "csatlakozz": "join in",
  "droni": "drones",
  "grabación": "recording",
  "doble": "double",
  "estado": "state",
  "clase10": "class 10",
  "wrnty": "warranty",
  "adecuado": "appropiate",
  "produktbeschreibung": "product description",
  "produktdatenblatt": "product data sheet",
  "carté": "card",
  "gratis": "free",
  "étui": "body",
  "haute": "high",
  "connectée": "connector",
  "kingsto": "kingston",
  "montre": "clock",
  "dzeniach": "days",
  "versione": "version",
  "czerwony": "red",
  "mobilnych": "mobile",
  "produktbewertungen": "product review",
  "prohlíže": "browsing",
  "prohlížeč": "browsing",
  "socios": "partner",
  "descuento": "discount",
  "archivo": "archive",
  "kolorze": "color",
  "fotocamere": "photo camera",
  "ma": "and",
  "negrollave": "black stick",
  "speedclass": "speed class",
  "standaardkorting": "standard discount",
  "standaard korting": "standard discount",
  "leden": "",
  "mémoires": "memory",
  "garantía": "warranty",
  "homologuée": "approved",
  "virtual": "virtual",
  "promocja": "special offer",
  "écriture": "writing",
  "expander": "expander",
  "stockage": "storage",
  "srebrny": "silver",
  "nymi": "them",
  "czowy": "frontal",
  "pomara": "orange",
  "innymi": "others",
  "paquete": "package",
  "datos": "data",
  "capacit": "capacity",
  "facile": "easy",
  "negra": "black",
  "fla": "flash",
  "korzy": "benefits",
  "leistung": "perfomance",
  "adaptersd": "sd adapter",
  "kartenleser": "card reader",
  "czarnym": "black",
  "negr": "black",
  "nagrywania": "recording",
  "micsd": "microsd",
  "highspeed": "highspeed",
  "device": "device",
  "rendimiento": "performance",
  "alte": "old",
  "speichergröße": "memory size",
  "clas": "class",
  "menor": "discount",
  "flashminne": "flash memory",
  "standardverpackung": "standard packaging",
  "schreibgeschwindigkeit": "write speed",
  "druga": "second",
  "deportes": "sports",
  "echte": "real",
  "generación": "generation",
  "porté": "gate",
  "años": "years",
  "experience": "experience",
  "jaune": "yellow",
  "odczytu": "reading",
  "laptops": "laptops",
  "multicolor": "multicolor",
  "anschlüsse": "connections",
  "mikro": "micro",
  "giallo": "yellow",
  "guter": "goods",
  "filmów": "movies",
  "acción": "action",
  "olvasó": "reading",
  "amarillo": "yellow",
  "jusquà": "until",
  "braun": "brown",
  "violeta": "violet",
  "cartm": "card",
  "kobn": "combination",
  "púrpura": "purple",
  "samsungmemorie": "samsung memory",
  "magasin": "store",
  "violett": "violet",
  "alto": "high",
  "mobilnymi": "mobil",
  "surfplatta": "tablet",
  "cámaras": "cameras",
  "ta": "facing",
  "tyce": "rods",
  "odczyt": "reading",
  "ultracompacto": "ultracompact",
  "komórkowymi": "cellular phones",
  "ligera": "light",
  "klasa": "class",
  "adhérents": "members",
  "remise": "discount",
  "wysuwane": "retractable",
  "ceny": "prices",
  "morado": "purple",
  "telefonami": "phones",
  "prestazioni": "performance",
  "polecana": "recommended",
  "modrá": "blue",
  "speicher": "memory",
  "transparente": "transparent",
  "antracita": "anthracite",
  "tillbehör": "accessories",
  "mano": "thousand",
  "lesegerät": "reader",
  "ancma": "",
  "doskona": "perfect",
  "flashcard": "flashcard",
  "photode": "photo",
  "technologies": "technologies",
  "bílá": "white",
  "essential": "essential",
  "speicherkarteteller": "memory card plate",
  "producten": "products",
  "winkel": "angle",
  "haal": "pick up",
  "powierzchni": "surface",
  "stylus": "stylus",
  "blan": "white",
  "kartenlesegerät": "card reader",
  "danych": "data",
  "fehér": "white",
  "stoarge": "storage",
  "blíster": "",
  "schnell": "fast",
  "usbllave": "usb stick",
  "klasy": "classes",
  "ksze": "book",
  "produits": "products",
  "ligne": "line",
  "retirez": "remove",
  "dataseg9": "data segment",
  "phonique": "phonic",
  "ulitmate": "ultimate",
  "spacing": "spacing",
  "mejor": "better",
  "stuks": "pieces",
  "hidden": "hidden",
  "minisdhc": "mini sd",
  "microsdx": " micro sd",
  "origine": "origin",
  "kingst": "kingston",
  "dark": "dark",
  "adapatador": "adapter",
  "section": "section",
  "przezroczysty": "transparent",
  "réseau": "network",
  "historia": "history",
  "electronica": "electronics",
  "minicase": "minicase",
  "isolation": "isolation",
  "ordinateur": "computer",
  "recoger": "collect",
}